apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kubernetes-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-kubernetes-app
  template:
    metadata:
      labels:
        app: my-kubernetes-app
    spec:
      containers:
      - name: my-kubernetes-app
        image: my-kubernetes-app:latest
        ports:
        - containerPort: 5000
