apiVersion: v1
kind: Service
metadata:
  name: my-kubernetes-app-service
spec:
  selector:
    app: my-kubernetes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
